# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

version: 2

project_name: beat

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: "filebeat"
    dir: "filebeat"
    binary: "filebeat"
    main: ./filebeat.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
archives:
  - id: "filebeat"
    ids:
      - "filebeat"
    formats: ["tar.gz"]
    name_template: "filebeat-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'