# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com

version: 2

project_name: beat

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=0

builds:
  - id: "filebeat"
    dir: "filebeat"
    main: ./filebeat.go
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - arm64
      - amd64
    flags:
      - -trimpath
    ldflags:
      - -s -w
#  - id: "auditbeat"
#    dir: "auditbeat"
#    main: ./auditbeat.go
#    goos:
#      - linux
#      - windows
#      - darwin
#    goarch:
#      - arm64
#      - amd64
#    flags:
#      - -trimpath
#    ldflags:
#      - -s -w
#  - id: "heartbeat"
#    dir: "heartbeat"
#    main: ./heartbeat.go
#    goos:
#      - linux
#      - windows
#      - darwin
#    goarch:
#      - arm64
#      - amd64
#    flags:
#      - -trimpath
#    ldflags:
#      - -s -w
#  - id: "metricbeat"
#    dir: "metricbeat"
#    main: ./metricbeat.go
#    goos:
#      - linux
#    goarch:
#      - arm64
#      - amd64
#    flags:
#      - -trimpath
#    ldflags:
#      - -s -w
#  - id: "winlogbeat"
#    env:
#      - CGO_ENABLED=0
#    dir: "winlogbeat"
#    main: ./winlogbeat.go
#    goos:
#      - linux
#      - windows
#      - darwin
#    goarch:
#      - arm64
#      - amd64
#    flags:
#      - -trimpath
#    ldflags:
#      - -s -w
archives:
  - id: "filebeat"
    ids:
      - "filebeat"
    formats: ["binary"]
    name_template: "filebeat_-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#  - id: "auditbeat"
#    ids:
#      - "auditbeat"
#    formats: ["binary"]
#    name_template: "auditbeat_-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#  - id: "heartbeat"
#    ids:
#      - "heartbeat"
#    formats: ["binary"]
#    name_template: "heartbeat_-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#  - id: "metricbeat"
#    ids:
#      - "metricbeat"
#    formats: ["binary"]
#    name_template: "metricbeat_-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"
#  - id: "winlogbeat"
#    ids:
#      - "winlogbeat"
#    formats: ["binary"]
#    name_template: "winlogbeat_-v{{ .Version }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'