name: elastic beat release by goreleaser

on:
  push:
    tags:
      - '*'

jobs:
  publish-dist:
    runs-on: ubuntu-24.04
    env:
      GO_VERSION: '1.24'
      GORELEASER_VERSION: '~> v2'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
          cache: false
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: release
        env:
          GITHUB_TOKEN: ${{ secrets.ASCENTSTREAM_GITHUB_TOKEN }}

  publish-image:
    needs: publish-dist
    runs-on: ubuntu-24.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.ASCENTSTREAM_DOCKER_USERNAME }}
          password: ${{ secrets.ASCENTSTREAM_DOCKER_PASSWORD }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: actions/checkout@v4
      - name: Download GitHub Release
        run: gh release download "$GITHUB_REF_NAME" --pattern "*-linux-*" --repo "$GITHUB_REPOSITORY" --dir dist
        env:
          GH_TOKEN: ${{ secrets.ASCENTSTREAM_GITHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./filebeat/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ascentstream/filebeat:${{ github.ref_name }}
